name: lgbmtrainingenv
dependencies:
  - gcc_linux-64
  - gxx_linux-64
  - python=3.7
  - pip
  - pip:
      - pandas
      - mlflow
      - azureml-mlflow
      - azureml-dataprep
      - azureml-interpret
      - featuretools==1.7.0
      - lightgbm
      - imbalanced-learn
      - interpret-community
      - holoviews
      - datashader

