$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: balancer
display_name: balancer
command: >-
  python balancer.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --balancer-mode ${{inputs.balancer_mode}}
  --type ${{inputs.type}}
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/balancer
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
  balancer_mode:
    type: string
  type:
    type: string
outputs:
  transformed_data:
    type: path
