$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: balancer
display_name: balancer
command: >-
  python balancer.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --type ${{inputs.type}}
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/balancer
environment: azureml:batch_training@latest
inputs:
  datasets_pkl:
    type: path
  type:
    type: string
outputs:
  transformed_data:
    type: path
