$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: balancer
display_name: balancer
command: >-
  python balancer.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/features
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
outputs:
  transformed_data:
    type: path
