$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: impute
display_name: calibrate
command: >-
  python calibrate.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --label ${{inputs.label}}
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/model
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
  label:
    type: string
outputs:
  transformed_data:
    type: path
