$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: downsample
display_name: downsample
command: >-
  python downsample.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/downsample
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
outputs:
  transformed_data:
    type: path
