$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: format
display_name: format
command: >-
  python format.py
  --input-data ${{inputs.input_data}}/datasets.pkl
  --label ${{inputs.label}}
  --replacements ${{inputs.replacements}}
  --datatypes ${{inputs.datatypes}}
  --drop-bools ${{inputs.drop_bools}}
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/format
environment: azureml:lgbmholoenv@latest
inputs:
  input_data:
    type: path
  label:
    type: string
  replacements:
    type: string
  datatypes:
    type: string
  type:
    type: string
  drop_bools:
    type: boolean
outputs:
  transformed_data:
    type: path
