$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: get_best_model
display_name: get_best_model
is_deterministic: False
command: >-
  python get_best_model.py
  --sweep-name ${{inputs.sweep_name}}
  --train-artifacts ${{inputs.train_artifacts}} 
  --primary-metric ${{inputs.primary_metric}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/model/get_best_model
environment: azureml:ltcftenv@latest
inputs:
  sweep_name:
    type: string
  train_artifacts:
    type: path
  primary_metric:
    type: string
outputs:
  transformed_data:
    type: path
