$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: impute
display_name: impute
command: >-
  python imputer.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/imputer
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
outputs:
  transformed_data:
    type: path
