$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: log_metrics
display_name: log_metrics
command: >-
  python log_metrics.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --project ${{inputs.project}}
  --destination-folder ${{inputs.destination_folder}}
  --downsample ${{inputs.downsample}}
  --drop-bools ${{inputs.drop_bools}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/common/log_metrics
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
  project:
    type: string
  destination_folder:
    type: string
  downsample:
    type: boolean
  drop_bools:
    type: boolean
outputs:
  transformed_data:
    type: path
