$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: log_metrics
display_name: log_metrics
command: >-
  python log_metrics.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --destination-folder ${{inputs.destination_folder}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/common
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
  destination_folder:
    type: string
outputs:
  transformed_data:
    type: path
