$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: register_model
display_name: register_model
command: >-
  python register_model.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --project ${{inputs.project}}
  --label ${{inputs.label}}
  --primary-metric ${{inputs.primary_metric}}
  --type ${{inputs.type}}
  --source ${{inputs.source}}
  --downsample ${{inputs.downsample}}
  --drop-bools ${{inputs.drop_bools}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/model/register_model
environment: azureml:lgbmholoenv@latest
inputs:
  datasets_pkl:
    type: path
  project:
    type: string
  label:
    type: string
  primary_metric:
    type: string
  type:
    type: string
  source:
    type: string
  downsample:
    type: boolean
  drop_bools:
    type: boolean
outputs:
  transformed_data:
    type: path