$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: register_dataset
display_name: register_dataset
command: >-
  python register_dataset.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/register_dataset
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
outputs:
  transformed_data:
    type: path