$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: register_model
display_name: register_model
command: >-
  python register_model.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/model
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
outputs:
  transformed_data:
    type: path