$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: register_dataset
display_name: register_dataset
command: >-
  python register_dataset.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --project ${{inputs.project}}
  --downsample ${{inputs.downsample}}
  --drop-bools ${{inputs.drop_bools}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/register_dataset
environment: azureml:batch_training@latest
inputs:
  datasets_pkl:
    type: path
  project:
    type: string
  downsample:
    type: boolean
  drop_bools:
    type: boolean
outputs:
  transformed_data:
    type: path