$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: set_header
display_name: set header
command: >-
  python set_header.py
  --input-data ${{inputs.input_data}}/transformed.csv
  --transformed_data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/set_header
environment: azureml:lgbmholoenv@latest
inputs:
  input_data:
    type: path
outputs:
  transformed_data:
    type: path

