$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: standardize
display_name: standardize
command: >-
  python standardize.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/features/standardize
environment: azureml:lgbmholoenv@latest
inputs:
  datasets_pkl:
    type: path
outputs:
  transformed_data:
    type: path
