$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: web_hook
display_name: web hook
command: >-
  python web_hook.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --url ${{inputs.url}}
  --param1 ${{inputs.param1}}
code: ../../src/pipeline/common/web_hook
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
  url:
    type: string
  param1:
    type: integer
