$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: web_hook
display_name: web hook
command: >-
  python web_hook.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --url ${{inputs.url}}
  --next-pipeline ${{inputs.next_pipeline}}
code: ../../src/pipeline/common
environment: azureml:ltcftenv@latest
inputs:
  datasets_pkl:
    type: path
  url:
    type: string
  next_pipeline:
    type: integer
